# Generated by Django 5.2.7 on 2025-11-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_moderate', 'Can moderate reviews and comments')]},
        ),
    ]
