# Generated by Django 5.2.7 on 2025-11-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
