# Generated by Django 5.2.7 on 2025-11-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0003_alter_user_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='title',
        ),
    ]
