# Generated by Django 5.2.7 on 2025-11-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0005_emailcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
