# Generated by Django 5.2.7 on 2025-11-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name']},
        ),
    ]
