# Generated by Django 5.2.7 on 2025-11-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0007_rename_titles_title_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
