# Generated by Django 5.2.7 on 2025-11-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0009_alter_review_options_alter_title_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
